# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  Major: '0'
  Minor: '1'
  Patch: '0'

jobs:
  - job: BuildWebRTC
    displayName: 'Building WebRTC'
    pool: 'Default'
    timeoutInMinutes: 240
    steps:
    - script: echo Hello, world!
      displayName: 'Dummy step'

    - script: envWin32.bat && python webrtc.py
      displayName: 'Generating 32-bit artifacts'

    - script: envWin64.bat && python webrtc.py
      displayName: 'Generating 64-bit artifacts'

    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/build-windows-x86_32
        artifact: WebRTC-static-windows-x86_32
    
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/build-windows-x86_64
        artifact: WebRTC-static-windows-x86_64
        
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/build-windows-x86_32/include'
        Contents: '**'
        TargetFolder: '$(System.DefaultWorkingDirectory)/build/native/include'
        CleanTargetFolder: true
        preserveTimestamp: true
      
      
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/build-windows-x86_32/lib'
        Contents: 
          webrtc.lib
          webrtc-common.lib
        TargetFolder: '$(System.DefaultWorkingDirectory)/build/native/Win32/Release'
        CleanTargetFolder: true
        preserveTimestamp: true
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/build-windows-x86_64/lib'
        Contents: 
          webrtc.lib
          webrtc-common.lib
        TargetFolder: '$(System.DefaultWorkingDirectory)/build/native/x64/Release'
        CleanTargetFolder: true
        preserveTimestamp: true
    
    - task: NuGetCommand@2
      inputs:
        command: 'pack'
        versioningScheme: byPrereleaseNumber
        packagesToPack: $(System.DefaultWorkingDirectory)/LiquidSky.WebRTC.Static.Build.nuspec
    
    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        publishVstsFeed: 'WebRTC-build-feed'
        allowPackageConflicts: true

