# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  Major: '0'
  Minor: '1'
  Patch: '0'


jobs:
  - job: BuildWebRTC
    displayName: 'Building WebRTC'
    pool: 'Default'
    timeoutInMinutes: 240
    steps:
    - script: echo Hello, world!
      displayName: 'Dummy step'

    - script: envWin32.bat && python webrtc.py
      displayName: 'Generating 32-bit artifacts'

    #- script: envWin64.bat && python webrtc.py
    #  displayName: 'Generating 64-bit artifacts'

    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/build-windows-x86_32
        artifact: WebRTC-static-windows-final-x86_32
    - task: PublishBuildArtifacts@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/build-windows-x86_32
        artifactName: WebRTC-static-windows-final-x86_32

    #- task: PublishPipelineArtifact@1
    #  inputs:
    #    pathToPublish: $(System.DefaultWorkingDirectory)/build-windows-x86_64
    #    artifactName: WebRTC-static-windows-x86_64

    #- task: NuGetCommand@2
    #  inputs:
    #    command: pack
    #    versioningScheme: byPrereleaseNumber
    #    majorVersion: '$(Major)'
    #    minorVersion: '$(Minor)'
    #    patchVersion: '$(Patch)'
    #    packagesToPack: $(System.DefaultWorkingDirectory)/build-windows-x86_32
